# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mybrowser.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def back(self):

        print('back')

    def forward(self):

        print('forward')

    def reload(self):

        print('reload')

    def goAddress(self):

        print('goAddress')

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1052, 885)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 951, 141))
        self.groupBox.setObjectName("groupBox")
        self.backButton = QtWidgets.QPushButton(self.groupBox)
        self.backButton.setGeometry(QtCore.QRect(10, 50, 51, 51))
        self.backButton.setObjectName("backButton")

        self.backButton.clicked.connect(self.back)



        self.inputUrlArea = QtWidgets.QLineEdit(self.groupBox)
        self.inputUrlArea.setGeometry(QtCore.QRect(170, 60, 721, 41))
        self.inputUrlArea.setObjectName("inputUrlArea")
        self.refreshButton = QtWidgets.QPushButton(self.groupBox)
        self.refreshButton.setGeometry(QtCore.QRect(60, 50, 51, 51))
        self.refreshButton.setObjectName("refreshButton")
        self.forwardButton = QtWidgets.QPushButton(self.groupBox)
        self.forwardButton.setGeometry(QtCore.QRect(110, 50, 51, 51))
        self.forwardButton.setObjectName("forwardButton")
        self.goButton = QtWidgets.QPushButton(self.groupBox)
        self.goButton.setGeometry(QtCore.QRect(890, 50, 51, 51))
        self.goButton.setObjectName("goButton")
        self.webView = QtWebKitWidgets.QWebView(Form)
        self.webView.setGeometry(QtCore.QRect(30, 160, 951, 701))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")

        self.retranslateUi(Form)
        self.backButton.clicked.connect(self.webView.back)
        self.refreshButton.clicked.connect(self.webView.reload)
        self.forwardButton.clicked.connect(self.webView.forward)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.backButton.setText(_translate("Form", "＜"))
        self.refreshButton.setText(_translate("Form", "Refresh"))
        self.forwardButton.setText(_translate("Form", "＞"))
        self.goButton.setText(_translate("Form", "Go"))
#from PyQt5 import QtWebKitWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWebEngineWidgets import *
from PyQt5.QtWidgets import *
from PyQt5.QtWebKitWidgets import QWebPage

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
